### ISSUE TITLE
API questions

### ISSUE THREAD

**Issue by MichaelXavier** [AndrewRademacher/drifter#4]
Had a couple minor points to discuss on the project's API. I'm happy to implement these features.

First, it seems like the library should provide a helper function for the common case of taking a pre-ordered list and deriving dependencies from that ordering. I have a working example [here](https://github.com/MichaelXavier/drifter/commit/2417acb02547884d8735646aa18f6a0a1097eabf#diff-f5dfd5602ec2cb1365b3563bfef5a2afR105). In most cases I think this will be the common use case. If I were to use drifter today I'd probably have a migrations module that had a simple list of changes.

Secondly, when implementing the tests, I added a test instance to drifter and realized that my migration function had to opt into using `resolveDependencyOrder`. This seems wrong. Dependency order resolution is something core to the library rather than any particular backend. One immediate idea is to have the class function be `migrateOne :: DBConnection a -> Change a -> EitherT String IO ()`, and then export separately `migrate :: DBConnection a -> [Change a] -> EitherT String IO ()` implemented in terms of `migrateOne` and `resolveDependencyOrder`.

**Comment by 3noch** [comment]
This seems to be done now?
