### ISSUE TITLE
add drifter-sqlite

### ISSUE THREAD

**Issue by legrostdg** [AndrewRademacher/drifter#7]
It would be nice to have sqlite bindings!

**Comment by MichaelXavier** [comment]
Agreed. It should be quite simple to implement with the [postgresql-simple driver](https://github.com/MichaelXavier/drifter-postgresql) as a pattern. However, it is worth noting this would be a separate library, not a PR for drifter.

**Comment by MichaelXavier** [comment]
@legrostdg http://hackage.haskell.org/package/drifter-sqlite
